### ISSUE TITLE
Change the path

### ISSUE THREAD

**Issue by bilalmirza74** [WebDevSimplified/React-Simplified-Beginner-Projects#1]
change the path of main.jsx in index.html
<script type="module" src="/src/main.jsx"></script> ==> <script type="module" src="./src/main.jsx"></script>

**Comment by DelphiCoder** [comment]
Kyle has it done correctly.  If you are having an issue, then you are not serving up the page using something like live-sever in VS Code.  Hopefully you are not just dragging the `index.html` file into the browser as the code is meant to be served up from a server. Adding the dot at the beginning of the path is only useful if you wish to serve the page from a subdirectory.  Which these demos were not designed to do as they are supposed to represent the site and not a subdirectory of the site.

**Comment by WebDevSimplified** [comment]
These files are automatically generated by Vite and are not meant to be changed so I am leaving it as is.
