### ISSUE TITLE
reactsimplified.com signup form broken

### ISSUE THREAD

**Issue by replete** [WebDevSimplified/React-Simplified-Beginner-Projects#2]
This probably isn't the right repo, but  wanted to report that the signup form is broken at reactsimplified.com with default ublock origin (convertkit.com) - might be worth including a message for this common scenario:

![Screenshot 2023-04-18 at 07 41 22](https://user-images.githubusercontent.com/812139/232693062-cd7c5966-210c-4752-80e5-cee727e95aa1.png)

Was hoping your course would be available to use after seeing your youtube video from a few days ago. Let me know if you need a beta tester.

**Comment by WebDevSimplified** [comment]
Hey. Thanks for reporting this issue. I just tried installing this ad blocker and submitting this form and I was not able to trigger the error you are seeing. I tried with multiple different emails, names, etc, but nothing would cause it to fail.

Is there maybe a specific setting you have enabled that is blocking it? Also, do you see the request/script being blocked in the extension?

**Comment by replete** [comment]
Hi Kyle,

I probably submitted this report too soon as I was rushing between commitments - this is probably a wontfix due to being a hardened privacy user, for a moment I forgot that I'd tightened things down. Still, I don't quite understand why setting noop on convertkit (ublock origin override) still resulted in this error:

![Screenshot 2023-04-18 at 14 48 13](https://user-images.githubusercontent.com/812139/232797808-20575d56-cd84-48bd-80a8-159463a47014.png)

Disabling ublock entirely for the site was successful, so I suppose this is some kind of quirk of my set up (which still doesn't quite make sense to me and thus not really a problem for most of your users.

I wanted to commend you on [this video](https://www.youtube.com/watch?v=Rh3tobg7hEo) by the way. A great intro to me as a seasoned frontend developer who has been out of the industry for 5 years. I was hoping your course would be available as I am looking for the best materials with which to re-skill in React and catch up on my rusty but not terrible FE skills.

Thanks Kyle, from sunny North Wales

Phil

**Comment by replete** [comment]
Also, it was fun to follow along to this video and convert to TypeScript as I went. So many questions about architecture and conventions...

**Comment by WebDevSimplified** [comment]
Thanks for the detailed information. You are correct in that this is not really something I can fix since it seems to be more an issue with ConvertKit being a large email provider so they are being blocked because of that.

Also, I am really glad you enjoyed that video. It is hard to make those crash course style videos as there is so much to cover in such limited time, but I am glad this video was able to help.
